// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmqysmbyxsbcwxgnumru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcXlzbWJ5eHNiY3d4Z251bXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MjgwNTksImV4cCI6MjA1NjQwNDA1OX0.UnxOViwYS0JR1rDJz2mU9Pll_kyC5_BQCSXDObNsR3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);